apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: layer2
  namespace: metallb-system
spec:
  addresses:
  - 172.18.1.1-172.18.1.10
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
